---
- unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/

- name: Install dependencies
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build Backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Run PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run start
