AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Creates EC2 instance with Prometheus using imports from network.yml
  Following https://codewizardly.com/prometheus-on-aws-ec2-part1/
Parameters:
  AccessKey:
    Description: Access Key
    Type: String
    Default: "-"
  SecretKey:
    Description: Access Key
    Type: String
    Default: "-"
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: udacity
      DisableApiTermination: false
      ImageId: ami-05f7491af5eef733a  #ubuntu
      InstanceType: t3.medium
      Monitoring: true
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: "0"
        GroupSet: 
        - !ImportValue prometheusSecurityGroup
        SubnetId: !Select [0, !Split [",", !ImportValue network-PublicSubnets]]
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            sudo useradd --no-create-home prometheus
            sudo mkdir /etc/prometheus
            sudo mkdir /var/lib/prometheus  

            wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
            tar xvfz prometheus-2.19.0.linux-amd64.tar.gz      
            sudo cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
            sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
            sudo cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
            sudo cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
            sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
            rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

            cat <<"EOF" > /etc/prometheus/prometheus.yml
            global:
              scrape_interval: 1s
              evaluation_interval: 1s

            scrape_configs:
              - job_name: 'node'
                ec2_sd_configs:
                  - region: eu-central-1
                    access_key: ${AccessKey}
                    secret_key: ${SecretKey}
                    port: 9100
            EOF

            cat <<"EOF" > /etc/systemd/system/prometheus.service
            [Unit]
            Description=Prometheus
            Wants=network-online.target
            After=network-online.target
            [Service]
            User=prometheus
            Group=prometheus
            Type=simple
            ExecStart=/usr/local/bin/prometheus \
                --config.file /etc/prometheus/prometheus.yml \
                --storage.tsdb.path /var/lib/prometheus/ \
                --web.console.templates=/etc/prometheus/consoles \
                --web.console.libraries=/etc/prometheus/console_libraries

            [Install]
            WantedBy=multi-user.target
            EOF

            sudo chown prometheus:prometheus /etc/prometheus
            sudo chown prometheus:prometheus /usr/local/bin/prometheus
            sudo chown prometheus:prometheus /usr/local/bin/promtool
            sudo chown -R prometheus:prometheus /etc/prometheus/consoles
            sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
            sudo chown -R prometheus:prometheus /var/lib/prometheus

            sudo systemctl daemon-reload
            sudo systemctl enable --now prometheus
      Tags:
        - Key: Name
          Value: prometheus-server
Outputs:
  EC2PublicIP:
    Description: EC2PublicIP
    Value: !GetAtt EC2Instance.PublicIp
